### ISSUE TITLE
It doesn't work :( 

### ISSUE THREAD

**Issue by nickofbh** [HackIllinois/admissions-2017#1]
See title

**Comment by nickofbh** [comment]
```
vendor.bundle.js:14 Error: [$injector:unpr] Unknown provider: skillFilterFilterProvider <- skillFilterFilter
http://errors.angularjs.org/1.6.1/$injector/unpr?p0=skillFilterFilterProvider%20%3C-<div ui-view="" class="ng-scope">killFilterFilter
    at http://admissions.hackillinois.org/vendor.bundle.js:13:377
    at http://admissions.hackillinois.org/vendor.bundle.js:13:22392
    at Object.r [as get] (http://admissions.hackillinois.org/vendor.bundle.js:13:21294)
    at http://admissions.hackillinois.org/vendor.bundle.js:13:22477
    at Object.r [as get] (http://admissions.hackillinois.org/vendor.bundle.js:13:21294)
    at http://admissions.hackillinois.org/vendor.bundle.js:15:22088
    at fn (http://admissions.hackillinois.org/vendor.bundle.js:15:206)
    at hn (http://admissions.hackillinois.org/vendor.bundle.js:15:1251)
    at http://admissions.hackillinois.org/vendor.bundle.js:15:314
    at r (http://admissions.hackillinois.org/vendor.bundle.js:13:809)
```

**Comment by bluedrops** [comment]
resolved; yasha is a dummy

**Comment by sskhandek** [comment]
I would like to comment on the unprofessionalism of this. Simom, as a 498RK graduate, you are expected to hold the highest quality standards of web development. Not everyone's a "dummy"

**Comment by nickofbh** [comment]
Don't worry, fixed his comment

**Comment by bluedrops** [comment]
![klpk2mm](https://cloud.githubusercontent.com/assets/14851163/22866692/3eb05556-f140-11e6-817b-2c55b30097b4.jpg)
